


version: "3.3"
services:
  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - 8080:8080
    volumes:
      - ./mydata:/label-studio/data
    depends_on:
      - ml_backend  # Ensure the ML backend starts first
    networks:
      - label_studio_networks
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.label_studio
      - DJANGO_ALLOWED_HOSTS=label_studio,localhost,127.0.0.1,172.22.0.3,*
      - DEBUG=true
      - MEDIA_ALLOW_PUBLIC_ACCESS=True

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres

#    environment:
#      - DJANGO_SETTINGS_MODULE=core.settings.label_studio
#      - ALLOWED_HOSTS=*


  ml_backend:
    build:
      context: ./ml_backend  # Path to the directory containing the Dockerfile
    container_name: ml_backend
    ports:
      - 9090:9090
    networks:
      - label_studio_networks
    volumes:
      - ./logs:/app/logs  # Ensure logs are stored outside the container

networks:
  label_studio_networks:
    driver: bridge



volumes:
  mydata:
